### PR TITLE
Bump click version it doesn't work with v6.7

### PR DESCRIPTION
**Pull request by tnsetting**

### CODE REVIEW

**Comment by matthewphsmith** [comment]
Thanks for finding and fixing this. Could you let me know what was failing on older versions of click? I'd like to understand what/if any problems might come up for our customers here at Lyft on old versions.

**Comment by tnsetting** [comment]
I have a container with a old version of flytekit 0.1.7 (with click v6.7)and tried to upgrade to 0.3.0b0 and it was not possible to start pyflyte with error:`__init__() got an unexpected keyword argument 'hidden'`.

Here is the stack trace:
`Traceback (most recent call last):
  File "/usr/local/bin/pyflyte", line 5, in <module>
    from flytekit.clis.sdk_in_container.pyflyte import main
  File "/usr/local/lib/python3.6/dist-packages/flytekit/clis/sdk_in_container/pyflyte.py", line 14, in <module>
    from flytekit.clis.sdk_in_container.register import register
  File "/usr/local/lib/python3.6/dist-packages/flytekit/clis/sdk_in_container/register.py", line 53, in <module>
    def register(ctx, pkgs=None, test=None):
  File "/usr/local/lib/python3.6/dist-packages/click/decorators.py", line 170, in decorator
    _param_memo(f, OptionClass(param_decls, **attrs))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1460, in __init__
    Parameter.__init__(self, param_decls, type=type, **attrs)
TypeError: __init__() got an unexpected keyword argument 'hidden'
`

**Comment by honnix** [comment]
This option is only available since 7.0 I think.

https://click.palletsprojects.com/en/7.x/api/?highlight=hidden#click.Option
vs.
https://click.palletsprojects.com/en/6.x/api/?highlight=hidden#click.Option

**Comment by slai** [comment]
Oops, forgot to check the version when I added that. Thanks for fixing @tnsetting!
